### ISSUE TITLE
Config file is not visible

### ISSUE THREAD

**Issue by ViktorAksionov** [bjornbjorn/SEO-Lite#20]
I checked in EE v2.7.3 and EE v2.10.1
I downloaded the latest version of SEO lite v1.4.9.3(bjornbjorn-SEO-Lite-release-1.4.9.3-5-gcedc84e.zip),  but in file "upd.seo_lite.php" I see v 1.4.10.

I added in seo_lite/config/seolite.php
```
$config['seolite_extra'] = array(
    '1' => array(
        'image' => array(
            'field_id' => 27,                   
            'field_type' => 'file',
        )
    )
);
```

In the file mod.seo_lite.php on line ~180 you have checking:
```
if($this->EE->config->item('seolite_extra'))
```
which always returns false, as result I cannot use {extra:image}

Any idea why it doesn't work?

**Comment by bjornbjorn** [comment]
Hi,

I guess it should be documented better but this config goes in your ExpressionEngine config file since it is site specific.

If you're using FocusLab's master config you can put it in config.master.php to apply it all environments, or if you're using vanilla EE it would go in system/expressionengine/config/config.php

**Comment by ViktorAksionov** [comment]
Thanks for explanation.

After putting it in the main global expressionengine/config/config.php it start to work.

Cheers
